name: npm (latest)
on: [push]
jobs:
  npm:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn
      - run: npm i -g yarn@1
      - run: yarn config set network-timeout 300000
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npx pleb@4 publish
